USE [Stat]
GO

CREATE NONCLUSTERED INDEX [ix01StatTypeNchar50] ON [mtb].[StatTypeNchar50]
(
	[BatchLogId] ASC
)
INCLUDE([PartitionId],[KeyElementId],[StatId],[StatValue]) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [FG_Mtb]
GO


