USE [Stat]
GO

CREATE UNIQUE NONCLUSTERED INDEX [ux01StatGroupMaxBatch] ON [stat].[StatGroupMaxBatch]
(
	[StatGroupId] ASC,
	[StatGroupMaxBatchId] ASC,
	[MaxBatchLogId] ASC,
	[DateActivated] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [FG1]
GO


